### ISSUE TITLE
Running average?

### ISSUE THREAD

**Issue by altf4** [zyphlar/pinger#3]
I started writing a feature to toggle the display of a running average of the pings in the current log. However, it wasn't immediately clear to me how error pings should be handled. 

Simply ignoring them doesn't feel accurate, as it would make the average higher than it should be, and probably defeat the purpose of displaying it. (Keeping an eye on your network quality)

But how do you numerically account for the missing ping in an average? 

Perhaps a running average feature just doesn't make sense in this context.

**Comment by zyphlar** [comment]
@altf4 I just implemented a simple running average; it's a simple average so failures count as -1 which is wrong, but the number is still somewhat useful for now.
