### ISSUE TITLE
Graphical plot of latencies

### ISSUE THREAD

**Issue by altf4** [zyphlar/pinger#4]
I'm thinking something like Cairo for drawing 2D graphs ought to work. There's even plotting libraries made from it, with python bindings.

http://cairoplot.sourceforge.net/index.html

For instance, Indicator Multiload uses Cairo to draw the performance graphs:

https://launchpad.net/indicator-multiload

**Comment by zyphlar** [comment]
@altf4 I just added double graphs and colors, I'm pretty happy with the graphics now so I'll close this. If you want to do a libnotify feature, feel free to contribute :)
